<?php

function displayPhoto($list, $nb) {
    for ($z = 0; $z < count($list); $z ++) {
        if ($z == 1) { // show only 1 picture
            echo "<div class='spoil'>";
        }

// picture display
        echo "<figure><a href='" . $list[$z]['path'] . "'>";
        echo "<img src='" . $list[$z]['path'] . "' alt='" .
        $list[$z]['title'] . "' />";
        echo "<figcaption>" . $list[$z]['title'] . "</figcaption>";
        echo "</a></figure>";

// end of div
        if ($z == count($list) - 1) {
            echo "</div>";
        } else
        if ($z < 1 && count($list) > 1) { // spoiler
// command
            echo "<a href='#' class='spoiler'><button>Voir plus</button></a>";
        }
// Stopping the loop at 5 (5 images show)
        if ($z == $nb) {
            break;
        }
    }
}

/**
 * Affiche la liste des villes avec distance
 * @param string $titre Le titre de la rubrique
 * @param string $page La page à ouvrir lors de la consultation
 * @param array $closestCity Liste des villes avec une notion de distance
 */
function displayCloseCityFromList($titre, $page, $closestCity) {

// title
    if (count($closestCity) > 0) {
        echo "<h2>" . $titre . "</h2>";
    }

// display the region
    for ($region = 0; $region < count($closestCity); $region ++) {
        echo "<h3>" . $closestCity[$region][0][0]['nom_region'] . "</h3>";

// display the county
        for ($departement = 0; $departement < count($closestCity[$region]); $departement ++) {
            echo "<h4>" . $closestCity[$region][$departement][0]['num_departement'];
            echo " - " . $closestCity[$region][$departement][0]['nom_departement'] .
            "</h4>";

// display the city
            for ($ville = 0; $ville < count($closestCity[$region][$departement]); $ville ++) {
// Show the city and distance between this city and the current
// working city
                echo "<a href='" . $page . "?code=";
                echo $closestCity[$region][$departement][$ville]['id_ville'];
                echo "' >";
                echo $closestCity[$region][$departement][$ville]['nom_ville'];
                echo " ( ";
                echo round($closestCity[$region][$departement][$ville]['distance'], 2);
                echo "km )</a><br>";
            }
        }
    }
}

// Show the city from a list generated by a preview request
function displayCity($title, $page, $listeCity) {
// List city
    $city = $listeCity;
// title
    echo "<h2>$title</h2>";

    if ($city == null || count($city) == 0) {
        echo "Pas de villes disponibles";
    }

// display the region
    for ($region = 0; $region < count($city); $region ++) {
        echo "<h3>" . $city[$region][0][0]['nom_region'] . "</h3>";

// display the county
        for ($departement = 0; $departement < count($city[$region]); $departement ++) {
            echo "<h4>" . $city[$region][$departement][0]['num_departement'];
            echo " - " . $city[$region][$departement][0]['nom_departement'] .
            "</h4>";

// display the city
            for ($ville = 0; $ville < count($city[$region][$departement]); $ville ++) {
// Show the city and distance between this city and the current
// working city
                echo "<a href='" . $page . "?code=";
                echo $city[$region][$departement][$ville]['id_ville'];
                echo "' >";
                echo $city[$region][$departement][$ville]['nom_ville'];
                echo "</a><br>";
            }
        }
    }
}

// Get the city from SQL request and show it
function displayCityBySQL($title, $page, $sql) {
    displayCity($title, $page, getCity($sql));
}

// Affiche la liste des villes sous forme de tableau en fonction de la requete
function displayCityAsTable($title, $page, $sqlRq) {
    $db = connexionBD();

    $sql = "SELECT nom_r, num_departement, ville_departement, ville_id, ville_nom, nom,
                 ville_code_postal, ville_population_2012
	            FROM villes_france_free V, departements D, regions R
	            WHERE ville_departement = num_departement
	            AND D.num_region = R.num_region
                    AND ville_statut = 'A'";
    $sql .= $sqlRq;
    $sql .= ' ORDER BY nom_r, num_departement, ville_nom';

    $response = $db->query($sql);
    echo "<table id='table-sort' class='table table-striped table-bordered'>
    <thead>
    <tr>
    <th>Ville</th>
    <th>Département</th>
    <th>Région</th>
    <th>Code Postal</th>
    <th>Population</th>
    </tr>
    </thead>
    <tbody>";
    if ($response->rowCount() > 0) {
        while ($row = $response->fetch()) {

            echo "<tr>
            <td>" . $row["ville_nom"] . "</td>
            <td>" . $row["nom"] . "</td>
            <td>" . $row["nom_r"] . "</td>
            <td>" .
            $row["ville_code_postal"] . "</td>
            <td>" .
            $row["ville_population_2012"] . "</td>
            </tr>";
        }
    }
    echo "</tbody>
	</table>


	<script type='text/javascript'>

	$(document).ready( function () {
	    $('#table-sort').DataTable( {
        'lengthMenu': [[35, 45, 50, -1], [35, 45, 50, 'All']]
    } );
	} );

    </script>";
// close cursor
    $response->closeCursor();
}
